const CONSTANTS = {
  SECRET_TOKEN: process.env.SECRET_TOKEN || 'secret',
  SECRET_REFRESH_TOKEN: process.env.SECRET_REFRESH_TOKEN || 'secret_refresh',
  EXPIRES_IN_TOKEN: '15m',
  EXPIRES_IN_REFRESH_TOKEN: '30d',
  EXPIRES_REFRESH_TOKEN_DAYS: 30,
};

export { CONSTANTS };
